# Generated by Django 3.1.7 on 2021-07-02 18:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=150)),
                ('section_description', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('birthday', models.CharField(max_length=150)),
                ('website', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('long_description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
