# Generated by Django 3.1.7 on 2021-07-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=150)),
                ('section_description', models.CharField(max_length=255)),
                ('icon_one_title', models.CharField(max_length=150)),
                ('icon_one_number', models.IntegerField(default=19)),
                ('icon_two_title', models.CharField(max_length=150)),
                ('icon_two_number', models.IntegerField(default=19)),
                ('icon_three_title', models.CharField(max_length=150)),
                ('icon_three_number', models.IntegerField(default=19)),
                ('icon_four_title', models.CharField(max_length=150)),
                ('icon_four_number', models.IntegerField(default=19)),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='age',
            field=models.IntegerField(default=19),
        ),
        migrations.AddField(
            model_name='about',
            name='degree',
            field=models.CharField(default='Software Engineer', max_length=150),
        ),
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.CharField(default='bakhtwarefahim@gmail.com', max_length=150),
        ),
        migrations.AddField(
            model_name='about',
            name='freelance',
            field=models.CharField(default='YES', max_length=150),
        ),
    ]
