# Generated by Django 3.1.7 on 2021-07-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20210703_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon_d',
            field=models.CharField(default='put', max_length=150),
        ),
    ]
