# Generated by Django 3.1.7 on 2021-07-02 21:47

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_services_icon_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=150)),
                ('section_description', models.CharField(max_length=255)),
                ('portfolio_name', models.CharField(max_length=150)),
                ('portfolio_description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('category', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='resume/images/')),
            ],
        ),
    ]
