# Generated by Django 3.1.7 on 2021-07-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('None', 'None'), ('Web Development', 'Web Development'), ('Web Designing', 'Web Designing'), ('eCommerce', 'eCommerce'), ('WordPress', 'WordPress')], default='None', max_length=100),
        ),
    ]
